name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies and build frontend
      working-directory: ./frontend
      run: |
        npm install
        npm run build

    - name: Install dependencies and build backend
      working-directory: ./backend
      run: |
        npm install
        tsc

    - name: Build Docker images
      run: |
        docker-compose build
